### ISSUE TITLE
是否支持汉语方言训练呢？

### ISSUE THREAD

**Issue by Ecauchy** [CjangCjengh/MoeGoe#12]
粗略看了一眼函数名，暂时没有看到除了cleaner以外的，针对语言的适配。
所以，假设我使用一种方言拼音方案作为文本输入，方言语料作为语音输入（语保平台or自己采集），是否可以顺利让纸片人说方言呢？还是说仍然需要对代码做一些改动？
望不吝赐教。（顺便吐槽一下没有注释让我看源码看得好艰难……）

**Comment by CjangCjengh** [comment]
可以

**Comment by SRbone** [comment]
请问关于cleaner的内容（语言种类很多）有没有参考信息啊？
