### ISSUE TITLE
Japanese phonemes issue?

### ISSUE THREAD

**Issue by Norgus** [CjangCjengh/MoeGoe#24]
I noticed there was an issue with all 3 models I tested (and I tested at least 2 voices in each model) all had issues pronouncing [Yoon](https://en.wikipedia.org/wiki/Y%C5%8Don)
the (non-exhaustive but extensive) test text is
```
キャッチャー・ちょうきょう・ちゅうきゅう・カチューシャ・ショート・シュート・ひょうじ・ヒューズ・ファイア
```

Samples can be found here:
[MoeGoe_voices_test.zip](https://github.com/CjangCjengh/MoeGoe/files/10045512/MoeGoe_voices_test.zip)

In order the models used were [Bishoujo Mangekyou](https://github.com/Francis-Komizu/VITS#Mangekyo), HamidashiCreative, and Zero_no_Tukaima

It doesn't sound like this rather essential core part of Japanese speech is being correctly reproduced in any of the models I tested.

**Comment by CjangCjengh** [comment]
I tested the models of Zerotsukai and Hamikuri with the same text. It seemed quite normal (though with strange accent).
As for Bishoujo Mangekyou, the auther is not me.
[demo.zip](https://github.com/CjangCjengh/MoeGoe/files/10046429/demo.zip)

**Comment by Norgus** [comment]
Was the output comparable to what I got? I'd like to know if it's a local
problem or they really sound like that.

**Comment by Norgus** [comment]
I just noticed I haven't tried your models yet, I'll report back after
trying them.

**Comment by CjangCjengh** [comment]
> Was your output different from what I got?
Yes. The two wav files included in demo.zip are my outputs

**Comment by Norgus** [comment]
Thanks I was finally able to work out opening the zip on my phone and your output does sound right to me. Ill try a fresh download when I get back to my desktop, see if it fixes itself

**Comment by Norgus** [comment]
Sorry I'm not sure what I broke before but it works correctly on a fresh download.
