### ISSUE TITLE
RuntimeError: Error(s) in loading state_dict for SynthesizerTrn:size mismatch for enc_p.emb.weight: copying a param with shape torch.Size([43, 192]) from checkpoint, the shape in current model is torch.Size([40, 192]).

### ISSUE THREAD

**Issue by HIBIKl** [CjangCjengh/MoeGoe#28]
Hi,
I used the newest version of [vits](https://github.com/CjangCjengh/vits) in your repositories to train my own dataset, and the training process went well. However, when I tried to use MoeGoe to test my own model I encountered this error. I found that the "symbols" in _japanese_base.json_ has only 40 values, but MoeGoe said it needs 43 values. Maybe the model and code version don't match? If so or not, how can I solve this problem? :(

Anyway, thank you in advance.

**Comment by HIBIKl** [comment]
Finally I solved this problem by using the japanese_cleaners2 symbols in ./texts/symbols.py, and it works well.

**Comment by QFDG** [comment]
Hi i recently met the same problem.But in diffrence,i have used chinese_cleaner to train my dataset.So your ways to solve the problem seems not valid in my situation.
Which way do you think is possible to deal with it? I am looking forward to your reply. Thanks.

**Comment by HIBIKl** [comment]
> Hi i recently met the same problem.But in diffrence,i have used chinese_cleaner to train my dataset.So your ways to solve the problem seems not valid in my situation. Which way do you think is possible to deal with it? I am looking forward to your reply. Thanks.

对于你的问题，要使用训练代码symbols.py中的chinese_cleaners：
For your problems, you should check the _chinese_cleaners_ in ./text/symbols.py:
<img width="509" alt="image" src="https://user-images.githubusercontent.com/36318991/219003112-220aa0b0-0092-4ccd-9982-be8a86c93639.png">
把xxx.json中symbols的字符改为chinese_cleaners中的字符，注意要把字符转换为Unicode编码。希望能帮到你。
Then change the characters in symbols in xxx.json to characters in chinese_cleaners, pay attention to convert the characters to Unicode encoding. hope this helps.

**Comment by QFDG** [comment]
是这样吗
# chinese_cleaners
_pad        = '_'
_punctuation = ''\uff0c', '\u3002', '\uff01', '\uff1f', '\u2014', '\u2026''
_letters = ''\u3105', '\u3106', '\u3107', '\u3108', '\u3109', '\u310a', '\u310b', '\u310c', '\u310d', '\u310e', '\u310f', '\u3110', '\u3111', '\u3112', '\u3113', '\u3114', '\u3115', '\u3116', '\u3117', '\u3118', '\u3119', '\u311a', '\u311b', '\u311c', '\u311d', '\u311e', '\u311f', '\u3120', '\u3121', '\u3122', '\u3123', '\u3124', '\u3125', '\u3126', '\u3127', '\u3128', '\u3129', '\u02c9', '\u02ca', '\u02c7', '\u02cb', '\u02d9', ' ''
'''

**Comment by QFDG** [comment]
井号chinese_cleaners
_pad        = '_'
_punctuation = ''\uff0c', '\u3002', '\uff01', '\uff1f', '\u2014', '\u2026''
_letters = ''\u3105', '\u3106', '\u3107', '\u3108', '\u3109', '\u310a', '\u310b', '\u310c', '\u310d', '\u310e', '\u310f', '\u3110', '\u3111', '\u3112', '\u3113', '\u3114', '\u3115', '\u3116', '\u3117', '\u3118', '\u3119', '\u311a', '\u311b', '\u311c', '\u311d', '\u311e', '\u311f', '\u3120', '\u3121', '\u3122', '\u3123', '\u3124', '\u3125', '\u3126', '\u3127', '\u3128', '\u3129', '\u02c9', '\u02ca', '\u02c7', '\u02cb', '\u02d9', ' ''
'''

**Comment by QFDG** [comment]
但是我的chinese cleaners没绿，绿的是Korean,
![QQ截图20230215194909](https://user-images.githubusercontent.com/108403140/219024596-634196d6-52de-44b1-8ba7-14a5b5dac271.png)

**Comment by QFDG** [comment]
兄弟，爱死你了！ 我现在才发现我是chinese cleaners后面三个点忘记去掉了，那时候我还奇怪为什么chinese不变绿，上面的korean绿了，但是因为这个是生成那个数据集的cleaned文件，我看到正常生成后就没在意，以为不是这个原因。然后又去重新配置和设置其他参数去了，唯独没在意这个。我知道导致这个的原因可能很傻逼，但是我没想到这么傻逼。我宣布，我是宇宙无敌究极大傻逼
