### ISSUE TITLE
RuntimeError: Error(s) in loading state_dict for SynthesizerTrn

### ISSUE THREAD

**Issue by QFDG** [CjangCjengh/MoeGoe#35]
跑了500个epoch,结果最后推理的时候出错，只有我一个人这样吗，真的心态炸裂
D:\Program Files\MoeGoe\MoeGoe>"D:\Program Files\MoeGoe\MoeGoe\MoeGoe.exe" --escape[15888] Failed to execute script 'MoeGoe' due to unhandled exception!Traceback (most recent call last):  File "MoeGoe.py", line 105, in <module>  File "utils.py", line 58, in load_checkpoint  File "torch\nn\modules\module.py", line 1605, in load_state_dict    self.__class__.__name__, "
	".join(error_msgs)))RuntimeError: Error(s) in loading state_dict for SynthesizerTrn:	size mismatch for enc_p.emb.weight: copying a param with shape torch.Size([35, 192]) from checkpoint, the shape in current model is torch.Size([50, 192]).Path of a VITS model: Path of a config file:

**Comment by zwluoqi** [comment]
怎么说，同样问题...

**Comment by erDoubeYou** [comment]
@QFDG  可以请问一下你是怎么解决的吗
